[package]
name = "your-progress"
version = "0.1.0"
authors = ["cake.monotone <cake.monotone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-width = "0.1.7"